### ISSUE TITLE
Bulgarian Cyrillic variants

### ISSUE THREAD

**Issue by LibertyType** [adobe-type-tools/adobe-cyrillic-charsets#1]
There are notes in the Cyrillic sets pertaining to Bulgarian design variants, but I have not been able to find any information elsewhere covering some of the ones Adobe lists. Does Adobe have a tech document available that provides more information on these design variants?

**Comment by pauldhunt** [comment]
@MajusCorp what type of information are you looking for? A good starting place to look might be [Two Cyrillics: a Critical View on History](http://cyrillicsly.com/post/87139831485/two-cyrillics-a-critical-view-on-history).

**Comment by LibertyType** [comment]
I had already been to that site.

The information I seek has to do with validity of some alternates, in particular these:
_(Notes on the following are Adobe's with my additions in parens)_
yeru-cy -- uni044B -- Upright style requires alternate form for Bulgarian (I cannot find any other source agreeing on this).
gje-cy -- uni0453 -- Upright style requires alternate form for Bulgarian (I cannot find any other source agreeing on this).
iigrave-cy -- uni045D -- Upright style requires alternate form for Bulgarian (I find only one other source agreeing on this).

It would be very helpful to all if there was a single source documenting all the Bulgarian Cyrillic alternates. There may be one I haven't found.

**Comment by frankrolf** [comment]
You have seen this video I assume?
http://cyrillicsly.com/post/87982259290/for-our-talk-at-atypi-we-were-looking-for-a-way

**Comment by frankrolf** [comment]
> yeru-cy -- uni044B -- Upright style requires alternate form for Bulgarian

I would say it goes along with the rounder treatment of soft and hard sign.

> gje-cy -- uni0453 -- Upright style requires alternate form for Bulgarian

Since gje is an accented ghe (which in Bulgarian looks like a flipped Latin _s_), it makes sense for it to take the shape of the base glyph.

> iigrave-cy -- uni045D -- Upright style requires alternate form for Bulgarian

Same comment as gje. icyr has the style of a latin lowercase _u_ in Bulgarian. Accented letters adopt the shape of their base glyphs.

**Comment by frankrolf** [comment]
In addition to the statements made above, I would like to point out that some of the letters are not even used in Bulgarian. In a list of 50K words, I found no occurrence of ы, and only 16 of ѓ.
However, the stylistic considerations still hold true.
ѝ is a Bulgarian letter (https://en.wikipedia.org/wiki/I_with_grave_(Cyrillic) ), and the nature of accented glyphs dictates the alternate shape for the base glyph (see line 2 in the video above).

**Comment by LibertyType** [comment]
I had tried to view the video previously, but it's just not there. It looks as though it's loading, but the progress bar goes through to the end, then... nothing more but a choice of other promoted items.

As for your explanations, they make perfect sense. I had been thinking along those lines but wasn't sure my thinking was correct.

Thank you. I believe my questions have been answered.

**Comment by frankrolf** [comment]
@MajusCorp Great! Glad to hear.
For the video – maybe try on Vimeo directly?
https://vimeo.com/97358652

(no problems on my end)

**Comment by StefanPeev** [comment]
# What shall be done for Bulgarian Cyrillic .loclBGR
"In this [article](http://www.lettersoup.de/what-shall-be-done-for-bulgarian-cyrillic-loclbgr/) I would like to describe the differences between the Bulgarian and Russian Cyrillic. Then I will list the characters you have to include in your fonts if you like to make Bulgarian Cyrillic and the different ways you can make it work with the Open Type features. Lets start with which Letters are different between Russian and Bulgarian Cyrillic. I will specify them for both Sans and Serif typefaces."

## .loclBGR for Grotesque Typefaces

<img width="1187" alt="bildschirmfoto-2016-07-07-um-12 59 31" src="https://cloud.githubusercontent.com/assets/12949369/26671318/abacf3da-46bd-11e7-9a4c-d64c3147a68f.png">

## .loclBGR for Serif Typefaces

<img width="1233" alt="bildschirmfoto-2016-07-07-um-13 11 25" src="https://cloud.githubusercontent.com/assets/12949369/26671341/c8d1948e-46bd-11e7-9236-30a1609fc12b.png">

**Botio Nikoltchev**
Source: [lettersoup](http://www.lettersoup.de/what-shall-be-done-for-bulgarian-cyrillic-loclbgr/#prettyPhoto/1/)

**Comment by miguelsousa** [comment]
Also worth reading [Cyrillic script variations and the importance of localisation](http://www.fontsmith.com/blog/2016/10/12/cyrillic-script-variations-and-the-importance-of-localisation) by Krista Radoeva.
