### ISSUE TITLE
Ҿҿ missing in Adobe Cyrillic 3 

### ISSUE THREAD

**Issue by alexeiva** [adobe-type-tools/adobe-cyrillic-charsets#3]
These glyphs are missing from the Adobe Cyrillic 3 list. They are required for Abkhaz support
```
Ҿ uni04BE 
ҿ uni04BF
```

**Comment by tphinney** [comment]
Hey, thanks! I'll update it in my versions of AC-3 definition.

**Comment by frankrolf** [comment]
I am curious – in some instances, this letter shows a diaeresis, in others it does not.
@alexeiva, do you have an explanation for that?
![screen shot 2016-12-19 at 17 15 18](https://cloud.githubusercontent.com/assets/2049645/21334785/d5275924-c60e-11e6-8b16-11a551296d1b.png)

**Comment by alexeiva** [comment]
I haven't seen a Ҿ with dieresis before. Abkhaz does not use dieresis.

Could be the Ҿ w/dieresis was confused with these glyphs in SFNST
```
ӛ 04DB 
ӫ 04EB
```

**Comment by ilyaruderman** [comment]
it shouldn't be any dieresis in this one, for sure!

**Comment by miguelsousa** [comment]
@alexeiva Thanks!
