### ISSUE TITLE
Adobe Cyrillic 3: Ѳ́/ѳ́ should most likely be Ө́/ө́.

### ISSUE THREAD

**Issue by moyogo** [adobe-type-tools/adobe-cyrillic-charsets#4]
In Adobe Cyrillic 3, the Mongolian letter straight u is combined with acute: Ү́ ү́. If this is indeed used in Mongolian, it is most likely used to indicate stress on the vowel, like in other languages using the Cyrillic alphabet. Since Mongolian is also using the barred o, one would expect there to be barred o acute: Ө́ ө́. Instead there is fita acute: Ѳ́ ѳ́, which seems to be a mistake since both letters look similar.

**Comment by miguelsousa** [comment]
Makes sense. Fix coming.
